version: '3.8'

services:
  ai-story-generator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: ai-story-generator
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-story-network

  # Development service (optional)
  ai-story-generator-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-story-generator-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ai-story-network
    profiles:
      - dev

networks:
  ai-story-network:
    driver: bridge 